/**
 * Maintainer map: route file → logical chain + typical upstream (not exposed to clients).
 */
export const ROUTE_CHAIN_MAP: Record<string, { chain: string; upstream: string }> = {
  "app/api/analyze/route.ts": { chain: "analysis", upstream: "modal" },
  "app/api/analyze/recalculate/route.ts": { chain: "analysis", upstream: "modal" },
  "app/api/club-detect/route.ts": { chain: "analysis", upstream: "modal" },
  "app/api/upload-video/route.ts": { chain: "analysis", upstream: "gemini_edge" },
  "app/api/modal-gemini-forward/route.ts": { chain: "analysis", upstream: "modal" },
  "app/api/lab/route.ts": { chain: "lab", upstream: "edge_d1_r2_gemini" },
  "app/api/lab/compare/route.ts": { chain: "lab", upstream: "edge_d1" },
  "app/api/lab/trend/route.ts": { chain: "lab", upstream: "edge_d1" },
  "app/api/lab/export/route.ts": { chain: "lab", upstream: "edge_d1" },
  "app/api/lab/history/route.ts": { chain: "lab", upstream: "edge_d1" },
  "app/api/lab/[id]/route.ts": { chain: "lab", upstream: "edge_d1" },
  "app/api/lab/video/[id]/route.ts": { chain: "render", upstream: "r2" },
  "app/api/plus/route.ts": { chain: "plus", upstream: "modal" },
  "app/api/plus/posture-video/route.ts": { chain: "render", upstream: "modal" },
  "app/api/plus/precheck/route.ts": { chain: "plus", upstream: "edge_d1" },
  "app/api/plus/usage/route.ts": { chain: "plus", upstream: "edge_d1" },
  "app/api/prov3/analyze/start/route.ts": { chain: "analysis", upstream: "modal" },
  "app/api/prov3/analyze/job/[jobId]/route.ts": { chain: "analysis", upstream: "r2_modal" },
  "app/api/prov3/analyze/cancel/route.ts": { chain: "analysis", upstream: "modal" },
  "app/api/prov3/precheck/route.ts": { chain: "analysis", upstream: "edge_d1" },
  "app/api/lite/analyze-proxy/route.ts": { chain: "analysis", upstream: "modal" },
  "app/api/lite/network-hint/route.ts": { chain: "analysis", upstream: "edge" },
  "app/api/history/route.ts": { chain: "record", upstream: "d1_r2" },
  "app/api/history/[id]/route.ts": { chain: "record", upstream: "d1" },
  "app/api/history/upload-video/route.ts": { chain: "record", upstream: "r2" },
  "app/api/history/upload-video/presign/route.ts": { chain: "record", upstream: "r2" },
  "app/api/history/video/[id]/route.ts": { chain: "render", upstream: "r2" },
  "app/api/share/route.ts": { chain: "share", upstream: "d1" },
  "app/api/share/[token]/route.ts": { chain: "share", upstream: "d1" },
  "app/api/share/video/[token]/route.ts": { chain: "render", upstream: "r2" },
  "app/api/auth/route.ts": { chain: "auth", upstream: "edge" },
  "app/api/user/route.ts": { chain: "auth", upstream: "edge_d1" },
};
